spring.application.name=TranAnhDuong_PH55491_j6

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SOF306_De7;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
